name: Controller
favicon: null
layout_spectrum: 0.42998
typography_spectrum: 0.60389
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#423c2c'
    - '#cab98b'
    - '#b78d19'
    - '#736d5d'
    - '#ffffff'
  brandStrength: 0.6726615608204156
  lightness: 0.5944102839566767
  saturation: 0.7707295676227659
  rhythmicContrast: 0.5585258519276977
purpose: []
