name: Controller
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60389
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#423c2c'
    - '#cab98b'
    - '#b78d19'
    - '#736d5d'
    - '#ffffff'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
